### ISSUE TITLE
This condition will always return 'false' since the types 'UserEventType' and 'string' have no overlap.ts(2367)

### ISSUE THREAD

**Issue by arook** [headintheclouddev/typings-suitescript-2.0#100]
How should this scenario be handled?

thx.
<img width="834" alt="image" src="https://user-images.githubusercontent.com/385978/50500926-791c2700-0a8f-11e9-8a14-c7b9595bb1fa.png">

**Comment by MrRob** [comment]
Hello!

You'd want to use the UserEventType enumeration in that situation. So, it
would be like: if (ctx.type == ctx.UserEventType.EDIT)

Robbie

*Robin Mitchell*
President
503-957-8114 *US Mobile*
07376 230976 *UK Mobile*
robin.mitchell@headintheclouddev.com

Head in the Cloud Development
http://www.headintheclouddev.com
Check my calendar availability
<http://www.google.com/calendar/embed?src=robin.mitchell%40ndos.co>

**Comment by arook** [comment]
Great,Thanks!
