### ISSUE TITLE
Globals missing (toString, require, log, util.*) 

### ISSUE THREAD

**Issue by cancerberoSgx** [headintheclouddev/typings-suitescript-2.0#103]
globals toString(), require(), log() and util.* methods are missing. This is not a big deal, with the exception of toString() and require():

https://system.netsuite.com/app/help/helpcenter.nl?fid=chapter_4387171685.html

about toString():

> Consider this method a replacement for the instanceOf operator (which is not
supported). SuiteScript 2.0 members are immutable; you cannot construct or modify
a native SuiteScript 2.0 member. Consequently, if you attempt to call instanceOf, an
undefined error is thrown.

About require(): 

> Use the require() Function to achieve progressive loading of native SuiteScript 2.0 modules and custom modules. When you use the require() Function, dependencies are not loaded until they are needed. This can help increase script performance.

I tried to implement these, but since N.d.ts is exporting / is not possible to declare globals there - not sure how to do it. maybe N.d.ts needs to be refactored to use modules /namespaces. I wanted to track this problem in this issue. 

Also there's a problem with toString() since is already declared in dom library, and with require() since is already declared in @types/node dependency. 

Thanks, keep it up!

**Comment by ShawnTalbert** [comment]
For what it's worth, SS2.1 does seem to handle `instanceof`.
