### ISSUE TITLE
callback function in ResultSet.each() does NOT have the index argument 

### ISSUE THREAD

**Issue by arook** [headintheclouddev/typings-suitescript-2.0#106]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/fe951133e5650edd3c724f11c5111a13f985acbe/N/search.d.ts#L81

`Use a developer-defined function to invoke on each row in the search results, up to 4000 results at a time. The callback function must use the following signature:

boolean callback(result.Result result);

`

**Comment by MrRob** [comment]
Thank you, removed that in version 2019.1.2
