### ISSUE TITLE
N/action - ActionExecuteFunction - options type is FindGetOptions and not ExecuteOptions

### ISSUE THREAD

**Issue by accountingnerd** [headintheclouddev/typings-suitescript-2.0#126]
As the title says: In N/action.d.ts, the ActionExecuteFunction interface is incorrectly typing the ActionExecuteFunction options as FindGetOptions rather than ExecuteOptions. I confirmed this this morning (21-JAN-2020) when I pulled the latest version from GitHub.

I would try to submit a pull request, but I'm not familiar enough with Git (yet) to do that yet.

**Comment by MrRob** [comment]
Okay, I corrected that, I appreciate you reporting it!  I haven't actually found an occasion to use this module yet.  If you have success with it, it might be nice if you could share what you ended up doing.

**Comment by accountingnerd** [comment]
Thanks for updating that!

I used the action module to create a "Reallocate Revenue Arrangement"
workflow action script. The script unchecks the compliant flag, saves the
record, and then uses the Allocate action to allocate the revenue
arrangements.

Nothing huge or earth shattering, but if you make changes to a fair value
price record or a fair value formula, it's a lot easier to click one button
to reallocate than to edit, uncheck, save, and allocate. Especially if the
forms from SuiteSuccess hide that field.

--
AJC

Brevity and typos courtesy of my mobile device.
