### ISSUE TITLE
Can't build-and-upload more than 1 file

### ISSUE THREAD

**Issue by steven-t-h** [headintheclouddev/typings-suitescript-2.0#127]
I followed the YouTube and ReadMe to the letter, and was able to successfully upload a test script to NetSuite. However, when I attempted to create a new file in my SSV2 folder (again, named directly after the tutorial just to be safe) I get an error when running build-and-upload.

![image](https://user-images.githubusercontent.com/29719881/73417858-9ef5aa00-42e7-11ea-972a-c716a4beea23.png)

It also appears the TS file created when I first start the project is different (see TS logo). I'm a JS dev moving to TS so this is fairly new to me, but I'm lost for what could be happening here.

![image](https://user-images.githubusercontent.com/29719881/73417996-fbf16000-42e7-11ea-9647-923acea43b76.png)

**Comment by steven-t-h** [comment]
I should also note that if I create a new project and build everything up from scratch, it all works for a single file again. Basically I'd have to build a project for each script file in order to use the build-and-upload.

**Comment by MrRob** [comment]
Hey Steven!  That's odd, I've used build-and-upload for the whole directory recently so I know it does work in general.  A small but perhaps important detail - can you try naming your directory ssv2 instead of SSV2?  I'm not sure if its case-sensitive or not.

**Comment by steven-t-h** [comment]
@MrRob same issue unfortunately. What TS version are you using and what type of project when creating the WebStorm project?

**Comment by MrRob** [comment]
@steven-t-h Hmm, maybe it is related to the WebStorm project.  My code is just in a folder on my hard drive, and I open that folder directly in WebStorm.  Have you watched the YouTube video demonstrating how to set this up?  Its here: https://www.youtube.com/watch?v=yDw4ex8rlCA&t=354s

I use a few different versions of TypeScript.  I'm seeing version 3.7.2, 2.8.4, and 2.9.2 on a few of my NetSuite repositories.

**Comment by steven-t-h** [comment]
@MrRob it must have been. I found that as long as I initialize the project in VS Code, I'm able to pull the repo into Webstorm and it's working fine now. Very odd, but I can close this out now. Thanks for the feedback!
