### ISSUE TITLE
NodeJS Version

### ISSUE THREAD

**Issue by MrRob** [headintheclouddev/typings-suitescript-2.0#139]
I've had problems trying to use the newer versions of node, so currently I'm using version 11.15.0.  Has anybody had success getting the script uploader to work on Node 12 or 13?

**Comment by ShawnTalbert** [comment]
I just noticed this - but perhaps you meant to file the issue on a different repo? This one is just the TS typings, not the uploader util...

**Comment by MrRob** [comment]
@ShawnTalbert Hmm yea you're right.  I did file it here intentionally, but thinking about it from that perspective, I don't think it belongs here!
