### ISSUE TITLE
record.Type should be enumeration?

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#14]
just like `file.Type`, the enumeration for record types is named `Type` not `RecordTypes`.

I'd recommend we switch to a standard TS enumeration so `record.Type` can be used in type position. It should still be able to support custom records as plain strings.

e.g. 

```typescript
function foo(recType : record.Type | string) {
}

foo(record.Type.INVOICE)

foo('customrecord_foo_bar')

```

**Comment by johnogle222** [comment]
I just updated this in master.
