### ISSUE TITLE
Getting an error on ui list styles. registered as a string, but is enumerated as ListStyle.

### ISSUE THREAD

**Issue by Nic-Wolf** [headintheclouddev/typings-suitescript-2.0#141]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/37902ce03664385c04c44e7bdad8d024cd146ed4/N/ui/serverWidget.d.ts#L494

String makes sense for shorthand, but how about 
```
/** Sets the display style for this list */
    style: string | ListStyle;
```

**Comment by MrRob** [comment]
Good idea!  I set it to just style: ListStyle, as I'm pretty sure those enums support plain strings as well.  Updated in version 2020.1.8.
