### ISSUE TITLE
Update query, record, search Type enums

### ISSUE THREAD

**Issue by dylbarne** [headintheclouddev/typings-suitescript-2.0#142]
Can you update the Type enums for query, record, search modules?
There are some new types that were exposed in 20.1 that would be nice to have included.

Below are snippets that can be run in the Browser (on NS with appropriate modules loaded) to generate the types matching your specs:

`Object.keys(query.Type).map((e,i) => e + ' = "' + Object.values(query.Type)[i] + '"').sort().join(',\n')`

`Object.keys(record.Type).map((e,i) => e + ", // '" + Object.values(record.Type)[i] + "'").sort().join('\n')`

`Object.keys(search.Type).sort().join(',\n')`

**Comment by MrRob** [comment]
I appreciate the snippets!  The enums are updated in Version 2020.1.11.
