### ISSUE TITLE
Corrections for N/sftp

### ISSUE THREAD

**Issue by felipechang** [headintheclouddev/typings-suitescript-2.0#143]
Please add enum to SFTP

`export enum Sort {
    DATE,
    DATE_DESC,
    SIZE,
    SIZE_DESC,
    NAME,
    NAME_DESC,
}`

correct Connection.list

`list: (options: { path: string, sort: Sort }) => string[];`

and remove the N/search reference

**Comment by MrRob** [comment]
Okay, done in version 2020.1.10
