### ISSUE TITLE
Map/Reduce `mapContext.write()` signature expansion?

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#144]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/f288bf71076737ab8a3ee2b8c254beb1f457ee13/N/types.d.ts#L213

Per the docs, the `key` or `value` parameters can be either a string or an object (in the latter case, the object is automatically JSON.stringified() so they say).

**Comment by MrRob** [comment]
Sure, updated that in Version 2020.1.12!
