### ISSUE TITLE
Getting Error while running karam

### ISSUE THREAD

**Issue by msreddy09** [headintheclouddev/typings-suitescript-2.0#146]
```
PS D:\verticalsgit\verticalstypesscriptdemo> karma start
24 07 2020 12:40:55.923:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.8.2
24 07 2020 12:40:59.691:ERROR [compiler.karma-typescript]: src/TypeScript/src/app/HelloTypeScriptPage/main/VTD_CS_HelloTypeScriptPage.ts(8,29): error TS2307: Cannot find module 'N/types'.

24 07 2020 12:40:59.692:ERROR [compiler.karma-typescript]: src/TypeScript/src/app/HelloTypeScriptPage/main/VTD_Su_HelloTypeScriptPage.ts(8,29): error TS2307: Cannot find module 'N/types'.

```

Hence getting compilation error.

**Comment by ShawnTalbert** [comment]
Do you have your `tsconfig.json` setup with paths?

e.g.
```json
"paths": {
      "N/*": [
        "node_modules/@hitc/netsuite-types/N/*"
      ]
    }
```

**Comment by Rvice** [comment]
I have this same issue with tsc on my typescript files, and I used the suggested tsconfig settings. I even took the examples and get the same error. Maybe something else is missing?

output of tsc --showConfig

```
tsc --showConfig
{
    "compilerOptions": {
        "module": "amd",
        "target": "es5",
        "moduleResolution": "node",
        "sourceMap": false,
        "newLine": "lf",
        "experimentalDecorators": true,
        "noImplicitUseStrict": true,
        "baseUrl": "./",
        "lib": [
            "es5",
            "es2015.promise",
            "dom"
        ],
        "paths": {
            "N": [
                "node_modules/@hitc/netsuite-types/N"
            ],
            "N/*": [
                "node_modules/@hitc/netsuite-types/N/*"
            ]
        }
    },
    "files": [
        "./myFile1.ts",
        "./myFile2.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

I've tried module 'commonjs' as well without luck

**Comment by MrRob** [comment]
That tsconfig setup looks pretty similar to mine.  In case it helps, here are a couple of videos showing how to use this module alongside our script uploader:
- Demo in Windows using WebStorm (2021): https://www.youtube.com/watch?v=Wf_z7IpTaJU
- Demo on Mac using VS Code (2020): https://www.youtube.com/watch?v=Q9wrP5GrFTU
- Demo on Mac using WebStorm (2019): https://www.youtube.com/watch?v=yDw4ex8rlCA

**Comment by ShawnTalbert** [comment]
These sound like separate issues to me. I think the original poster meant to say _Karma_ not _Karam_ (whatever that is?). Karma runs in browser so I'm not sure what the use case is.

For issues with TS compilation we might want to open a separate github issue?

I can't remember why we have both `N` and `N/*` referenced separately in `tsconfig.json`. Maybe something in the commit history to reveal.

Overall @MrRob  I'd suggest a refresh of the tsconfig.json? For example, if you're scripting for SS 2.1 you can have TS target ES2019 and include library references for ES2019 stuff like `Map` and `Set`?

Finally, years ago I started using `UMD` as the module output so that the compiled JS can be used unmodified both in NetSuite (AMD) and unit tests (jest/commonjs/node).

**Comment by darrenhillconsulting** [comment]
@ShawnTalbert , I'd love to see an example of your `UMD` project and pick your brain on it.  I'm finding it difficult to use NetSuite's 'jest' solution with Typescript (current using tsjest).  Potential example?

**Comment by Rvice** [comment]
I changed my tsconfig file a bit, but not much different. Not sure where things magically started working, but now I'm all set.

I have not yet moved into the jest portion yet within typescript.

**Comment by ShawnTalbert** [comment]
> @ShawnTalbert , I'd love to see an example of your `UMD` project and pick your brain on it. I'm finding it difficult to use NetSuite's 'jest' solution with Typescript (current using tsjest). Potential example?

Darren, haven't I've previously sent you the entire webstorm template ready-to-go ZIP file?

I can share that again in the NS Slack if y'all want? It uses a `tsconfig.json` similar to the one here.

**Comment by ShawnTalbert** [comment]
This ticket is 1.5 years old with no response from the OP. Time to close it?

**Comment by darrenhillconsulting** [comment]
Ya
