### ISSUE TITLE
Missing EntryPoint for WorkflowAction

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#17]
Add the following to the index.d.ts file

namespace WorkflowAction {
        interface onActionContext {
            newRecord: N_record.Record;
            oldRecord: N_record.Record;
        }
        type onAction = (scriptContext?: onActionContext) => void;
    }

**Comment by darrenhillconsulting** [comment]
Sorry, ran out of time to generate a Pull Request

**Comment by ShawnTalbert** [comment]
this is somewhat orthogonal, but wondering if we can do away with the majority of the index.d.ts file in TS2.0 land

**Comment by johnogle222** [comment]
@ShawnTalbert yeah I'm curious about this possibility as well, but I'm not totally sure how would do it. Want to open up a separate issue on the topic?

**Comment by johnogle222** [comment]
UserEvents.WorkflowAction is now in place! Thanks :)
