### ISSUE TITLE
render.TemplateRenderer.renderAsPdfToResponse() should be renderPdfToResponse() (i.e., no "As" in the name)

### ISSUE THREAD

**Issue by steveklett** [headintheclouddev/typings-suitescript-2.0#175]
I don't see evidence that NetSuite changed the name, but who can be sure.
The [docs](https://netsuite.custhelp.com/app/answers/detail/a_id/44647/kw/TemplateRenderer.renderPdfToResponse()) are clear on the method name and I can confirm errors are thrown if renderAsPdfToResponse() is forced.

encountered with version 2020.2.16

**Comment by MrRob** [comment]
@steveklett Thank you for pointing this out!  I'll have a fix for this in the next release, which should be later this week.
