### ISSUE TITLE
Missing parameters on map&reduce summary iterator

### ISSUE THREAD

**Issue by tomaswatz** [headintheclouddev/typings-suitescript-2.0#178]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/acc2eb83118fdd63f0170fa0e558161f8bd00c01/N/types.d.ts#L289

The MapSummary's and ReduceSummary's keys.iterator().each() have three parameters not two.
```javascript
interface MapReduceSummaryIterator {
  each(callback: (key: string, executionCount: number, completionState: string) => boolean): void;
}
```
http://system.netsuite.com/app/help/helpcenter.nl?fid=section_4472745365.html

**Comment by MrRob** [comment]
Thank you!  Updating this in 2021.1.4

**Comment by tomaswatz** [comment]
No, thank you for this library!
However, you may have missed that the summarizeContext.output do have "key" and "value" and it is now connected to the same MapReduceIteratorContainer.
So you may need two *IteratorContainers.
