### ISSUE TITLE
N/redirect's ToRecordOptions interface type property missing record.Type

### ISSUE THREAD

**Issue by cxa-croper** [headintheclouddev/typings-suitescript-2.0#179]
`ToRecordOptions.type` could/should(?) be `string | Type` where `Type` is `record.Type`. I know this is not explicitly spelled out in the [docs](https://netsuite.custhelp.com/app/answers/detail/a_id/44841) themselves, but it appears to be correct in practice -- and even in the example at the Help Center page referenced above. I know, I know, one sign of insanity is trusting the Netsuite docs 😄

The same is likely true of `ToRecordTransformOptions.fromType` and `.toType`.

**Comment by MrRob** [comment]
I checked the examples and I think you're right. I'm updating this in 2021.1.4, thank you!

**Comment by cxa-croper** [comment]
Thanks @MrRob !
