### ISSUE TITLE
runtime.User missing `contact`

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#183]
looks like the `User` interface from `runtime.d.ts` is missing the `contact` property?

https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1554920187.html

Is this a case of erroneous NS documentation or can we add that field?

**Comment by MrRob** [comment]
@ShawnTalbert It does seem to be a thing, implementing in 2021.1.6, thank you!
