### ISSUE TITLE
record.delete return value is incorrect

### ISSUE THREAD

**Issue by cxa-croper** [headintheclouddev/typings-suitescript-2.0#188]
Here's the current code:
```javascript
/**
 * Delete a record object based on provided type, id and return the id of deleted record
 *
 * @governance 20 units for transactions, 4 for custom records, 10 for all other records
 *
 * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if type or id is missing
 *
 * @since 2015.2
 */
interface RecordDeleteFunction {
    (options: RecordDeleteOptions): void;
    promise(options: RecordDeleteOptions): Promise<void>;
}
```

The JSDoc correctly describes the return value per [Netsuite documentation](https://netsuite.custhelp.com/app/answers/detail/a_id/45157), but the actual interface returns `void` which is incorrect. It should return a number. I haven't used the promise version, so I can't speak directly to it, but I'd imagine that also needs updating.

Thanks!

**Comment by MrRob** [comment]
Fixed this in version 2021.1.11, thank you for reporting!
