### ISSUE TITLE
Button id should be optional in AddButtonOptions

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#19]
In the file typings-suitescript-2.0/N/ui/serverWidget.d.ts  

The interface AddButtonOptions

the **id** should be optional (as Netsuite will auto-assign one anyway)

Should look like this

interface AddButtonOptions {
    /** The internal ID of the button. If you are adding the button to an existing page, the internal ID must be in lowercase, contain no spaces, and include the prefix custpage. */
    id?: string;
    /** The label for this button. */
    label: string;
    /** The function name to be triggered on a click event. */
    functionName?: string;
}

**Comment by johnogle222** [comment]
Cool I didn't know that! Fixed :)
