### ISSUE TITLE
url.resolveRecord parameter recordType doesn't accept record.Type enums

### ISSUE THREAD

**Issue by tomaswatz** [headintheclouddev/typings-suitescript-2.0#194]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/1b42519cfb69a3859052352f0cf317b691bd016e/N/url.d.ts#L14

Since the record.Type enums are supposedly strings in NS. Either change the definition of that enum to strings or change the type of the recordType parameter so that it accepts 
```javascript
recordType: record.Type | string;
```

**Comment by MrRob** [comment]
We generally try to follow specifically what the module documentation says, but I can see how this would be helpful, so I've added it in version 2021.2.3

**Comment by tomaswatz** [comment]
When you say module documentation, do you mean the docs in the actual .js-files for the libraries, or the help regarding the module?

Why did you choose to have record.Type as numbers when it is referred to as strings in the help and the record.js module also has them as strings?

**Comment by ShawnTalbert** [comment]
My opinions only but:

* I recommend using the online help mostly, not the jsdocs for the libraries as the jsdocs have been traditionally rubbish. NFT has a similar situation with regards to what fields to provide on the base record types; we strongly align with the online help and only deviate when we empirically find the online help is erroneous.
* record.Type is an **enumeration**; as such even though the _values_ happen to be strings, using that fact violates the very abstraction that the enumeration is trying to provide. In other words `record.Type.ITEM` is an opaque representation - if under the covers NS has a string or a number or an object as the value it should be generally irrelevant to code using the enumeration. One last point to remember is that this library is type _declarations_, not _definitions_.  

IMHO the main motivation to allow `string` to slip in is for custom records - NS can't know ahead of time the ids for custom record types so it can't be in a pre-built enumeration.

**Comment by MrRob** [comment]
@ShawnTalbert Your insights are very helpful and much appreciated!

Yes, I go by the online Help rather than the jsdocs.  And I concur with Shawn Talbert's response about the enumerations - that is a much better than I would have been able to articulate.
