### ISSUE TITLE
util.d.ts not implemented correctly (compare to log.d.ts)

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#2]
Hey,

utild.ts should look like this

export function isArray(obj: Object): boolean;
export function isBoolean(obj: Object): boolean;
export function isDate(obj: Object): boolean;
export function isNumber(obj: Object): boolean;
export function isobject(obj: Object): boolean;
export function isRegExp(obj: Object): boolean;
export function isString(obj: Object): boolean;
export function nanoTime(): string;
export function each(iterable: Object, callback: Function): Object;
export function extend(receiver: Object, contributor: Object): Object;

**Comment by johnogle222** [comment]
Thanks again, Darren! These updates are applied now with some minor tweaks.
