### ISSUE TITLE
Search.load should allow both string id as well as number id 

### ISSUE THREAD

**Issue by martina-brokenrubik** [headintheclouddev/typings-suitescript-2.0#202]
Currently, it only allows for a string value (such as 'customsearch_mysearch') but it is also possible to load a Saved Search by using its internal ID number.

`search.load({
id:'customsearch_search',
type:search.Type.EMPLOYEE,
})`

should work as well as

```
search.load({
id:12345,
type:search.Type.EMPLOYEE,
})
```

Therefore id should be `string | number` and not just `string`.

Thanks!

**Comment by ShawnTalbert** [comment]
Just thought I'd mention  internal id is actually a `string`. They are strings of numbers, but still strings.

Still, we regularly use `number` for internalid values in NFT to catch some errors that plain `string` would miss.

**Comment by MrRob** [comment]
The NetSuite documentation (which is our best guide to defining this module) says the type of the id attribute is string.  While using a number does currently work, it is possible that this won't always work.  Thus I'd recommend always using a string for the search id ("12345").
