### ISSUE TITLE
N/query module incomplete

### ISSUE THREAD

**Issue by DenWav** [headintheclouddev/typings-suitescript-2.0#208]
I noticed a few inconsistencies (and at least one place where NetSuite's documentation appears to be wrong).

 * [`query.create(options)`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510275581.html): The [`options` type definition](https://github.com/headintheclouddev/typings-suitescript-2.0/blob/8f4ab7a9b8015e8b56992e4873d2318d15a39a53/N/query.d.ts#L174-L179) is missing the `columns`, `condition`, and `sort` fields.
 * [`query.Query.createCondition(options)`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510780329.html): The [`options.values`](https://github.com/headintheclouddev/typings-suitescript-2.0/blob/8f4ab7a9b8015e8b56992e4873d2318d15a39a53/N/query.d.ts#L56) type definition differs from what it's in the documentation - however I'm not sure which is right here. The docs say [`query.RelativeDate`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1544109440.html) and [`query.Period`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_158289614570.html) are also acceptable, which is missing in the type definition here. However, the type definition here also includes non-array values, which doesn't match the documentation's type definition. *But* the docs say:
   
   > An array of values to use for the condition. This value sets the [Condition.values](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510789525.html) property.
 
   And [`query.Condition.values`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510275060.html#subsect_1510789342) has a different set of types in its type definitions - including bare `number` which is missing in this type definition. I don't know which is right and which isn't, but based on the [code example for `query.Query.createCondition(options)`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510780329.html#subsect_1530621090), I think at the very least the type definition should be expanded to allow bare `number` (like it does for `string` and `boolean`).

 * [`query.Period`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_158289614570.html) and [`query.createPeriod(options)`](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_158289670344.html) appears to be missing

**Comment by MrRob** [comment]
Thank you for bringing this up!  I've addressed these issues in version 2022.1.3.  Please test the updates and close this issue if resolved.

**Comment by MrRob** [comment]
Hey Kyle,

I'm looking at the documentation here.  Do you mean like how they have on the example code:
`var firstCondition = myCustomerQuery.createCondition({
    fieldId: 'id',
    operator: query.Operator.EQUAL,
    values: 107
})`?

If so, I think I would opt not to add it, as the parameters definition above the example code does not include a plain number.  Their examples are often not great.

Thanks!

Robbie

**Comment by DenWav** [comment]
Makes sense - their documentation definition leaves a lot to be desired. Thanks!
