### ISSUE TITLE
addPageInitMessage should allow parameter with name message to input a message.Message

### ISSUE THREAD

**Issue by tomaswatz** [headintheclouddev/typings-suitescript-2.0#209]
This function now also allows a signature where the message property is a Message object.
![image](https://user-images.githubusercontent.com/79501240/159457527-14489c49-581b-4296-8394-3014e578f5e8.png)

https://github.com/headintheclouddev/typings-suitescript-2.0/blob/03665e15b97868d099103d7693cb515ea3612dce/N/ui/serverWidget.d.ts#L452

```typescript
addPageInitMessage(options: { message: Message } | MessageCreateOptions): void;
```

**Comment by MrRob** [comment]
Hello! Have you been able to test this successfully?  I tried it and when it shows in NetSuite the message just says [object Object].

**Comment by MrRob** [comment]
Okay, I've added this in version 2022.1.4, thank you!
