### ISSUE TITLE
Reduce index.d.ts to the minimum (and maybe rename it in the process)

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#21]
**index.d.ts**

with TS 2.0 we don't need the typings tool or other crutch to get all the NS types into scope. This is a request to reconsider the role of this `index.d.ts` file in a TS 2.0 world. 

Currently this file imports and re-exports all the modules - that should be unneeded as consumers would just import the `N/` modules themselves per standard practice in their script files.

Hence perhaps the index.d.ts file can be reduced to just defining typings that are not part of any of the `N/` modules, such as the `EntryPoints` declarations.  If so, maybe we can come up with an improved name for this file.

**Comment by johnogle222** [comment]
If we did this though would we lose the supported feature of importing 'N' and then just referencing the modules as properties of the N module? Or is TypeScript 2.0 smart enough to handle this?

**Comment by ShawnTalbert** [comment]
I'm not sure of the benefit of having properties of the `N` module? Or maybe I'm missing the point which is quite possible!

In all my scripts I import each N module on an as-needed basis, e.g.

```
import * as record from "N/record"
import * as http from "N/http"
```
That gives me a variable named 'record' just like the examples show in NS help, and I use it accordingly without anything else, and it makes it very clear which `N` modules my script depends upon.

If you want to keep the huge list of `import` then `export` of N modules in this file, could we at least separate the rest of the file (e.g. EntryPoints ) into a separate file?

**Comment by darrenhillconsulting** [comment]
I do the same ... expect

import record = require('N/record');
import http = require('N/http');

Is there a difference?

**Comment by johnogle222** [comment]
Right sorry, I was on a phone so typing out the example there was a bit harder.

This is totally valid and documented in SS2.0:

`import N = require('N');

N.record.create({type:'customer'})
...
`

If we removed all the import/export stuff in index.d.ts then this would start to throw errors I believe.

**Comment by ShawnTalbert** [comment]
requiring all of "N" would be quite wasteful no? and I haven't personally seen any NS examples suggesting the usage you outline above.

Can we go ahead and  leave your index.d.ts full of exports if you prefer, but separate out the other type declarations in there as per my original message above? That way I don't have to ever import index.d.ts.

These type declarations in that file are independent of the mass `export`s and don't really belong in a catchall index.d.ts any more than other declared types do, wouldn't you agree?

**Comment by johnogle222** [comment]
Yeah I agree it isn't a great pattern, but I'm trying to be complete as best I can here.

I agree with what you're saying. I moved the import/export full module from N/index.d.ts to /N.d.ts and I renamedthe EntryPoints definition to N/types.d.ts. This will obviously require you to change N/index to N/types in your codebase but I think this will be a good system moving forward.

I'm open to suggestions on a different name than N/types if anyone wants to comment. I'll push up this change in 2016.2.2 early next week most likely.

**Comment by johnogle222** [comment]
Okay 2016.2.2 is released now. EntryPoints now lives under N/types and is a separate file from the N.d.ts file that is there to support the 'N' module.

Thanks!
John
