### ISSUE TITLE
N/search: Typo made for Page interface

### ISSUE THREAD

**Issue by wuiyang** [headintheclouddev/typings-suitescript-2.0#225]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/ff139244f77a1d7afefb569daa4f20747fa9ae54/N/search.d.ts#L110-L118

The `PageRange` key should be `pageRange`, not `pagedRange`.

Relevant documentation:
https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1510878146.html

**Comment by MrRob** [comment]
Thanks, fixing this in 2022.2.6!
