### ISSUE TITLE
recordContext.d.ts - wrong type for record parameter

### ISSUE THREAD

**Issue by shradela** [headintheclouddev/typings-suitescript-2.0#245]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/65660b9c62721714789914798470238f8c1568de/N/recordContext.d.ts#L12

Hello, I have an issue with recordContext.getContext(), where parameter record has type string, but also in documentation inside recordContext.d.ts file it says object. Can it be switched to record.Record | record.ClientCurrentRecord ?
![image](https://user-images.githubusercontent.com/69766473/226585092-a89a3bd7-d71c-4abc-bbd4-be8c59ce5654.png)

This will follow documentation provided in NetSuite Help Center.
![image](https://user-images.githubusercontent.com/69766473/226585452-ba2f01a8-87e0-43dc-ad48-cb027be1f992.png)

**Comment by MrRob** [comment]
Sure thing, fixing this in version 2023.1.5, thanks for reporting this!
