### ISSUE TITLE
Record.setSublistValue(options)

### ISSUE THREAD

**Issue by keirk** [headintheclouddev/typings-suitescript-2.0#250]
https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4273166777.html

According to the docs the options.value should be number | Date | string | array | boolean, but SublistSetSublistValueOptions.value is string

`interface SublistSetSublistValueOptions {
    /** The internal ID name of the line item field being set. */
    id: string;
    /** The line number for this field (starts at 0). */
    line: number;
    /** The value for the field being set. */
    value: string;
}`

**Comment by ShawnTalbert** [comment]
Are you perhaps on a very old version of typings-suitescript?

The current definition for [SetSublistValueOptions](https://github.com/headintheclouddev/typings-suitescript-2.0/blob/390eb42ad8dce333f19c47b1dfdaaf31745fe08b/N/record.d.ts#L326) defines `value` as type `FieldValue` which is defined as 
```typescript
export type FieldValue = Date | number | number[] | string | string[] | boolean | null;
```

**Comment by MrRob** [comment]
@keirk I see the confusion here.  From the record module, you are correct, you can set a sublist value with a string, number, date, etc.  However, the interface you mentioned is from the N/ui/serverWidget module.  In the context of creating a sublist on a form, you can only set string values.  See: https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_456052185058.html
