### ISSUE TITLE
Internal imports shouldn't use "N/..." module names

### ISSUE THREAD

**Issue by bendemeyer** [headintheclouddev/typings-suitescript-2.0#252]
Most of the files in the `N` directory refer to each other using relative paths, but in a few places they use `N/somename` instead. There's no advantage to doing this, as far as I can tell, but it does break any projects that might want to use these types without changing their TypeScript config to point those paths at this project (for example, using both this project and the official NetSuite unit testing stubs library).

I think I've identified all the cases where this happens already, so if this is a desired change I can open a PR for it.

**Comment by bendemeyer** [comment]
I looked at this again and realized it was pretty small so I just went ahead and created a PR: https://github.com/headintheclouddev/typings-suitescript-2.0/pull/253/files

**Comment by MrRob** [comment]
Merged, thank you!
