### ISSUE TITLE
Add EntryPoints.Reslet

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#26]
Add the following to the /N/index.d.ts file

namespace Restlet {
            interface getContext {
            }
            interface postContext {
            }
            interface putContext {
            }
            type get = (scriptContext?: getContext) => string|Object;
            type post = (scriptContext?: postContext) => string|Object;
            type put = (scriptContext?: putContext) => string|Object;
        }

**Comment by johnogle222** [comment]
This is released now in 2016.2.2. I modified it a bit from your starting point here. Check out example-RESTlet.ts for the pattern.

Thanks!
John
