### ISSUE TITLE
piRemoval CreateTaskOptions fieldIds type

### ISSUE THREAD

**Issue by steven-t-h** [headintheclouddev/typings-suitescript-2.0#272]
The Netsuite documentation for [piremoval.createTask](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_156174907211.html#subsect_156174921935) shows fieldIds as `number[]`. However, fieldIds are strings (and the demo shows strings in use).

Should the interface for CreateTaskOptions be updated to allow for `string[]`?

**Comment by MrRob** [comment]
@steven-t-h Oh good shout, you're probably right.  I've never used that module to be honest.  Are you possibly able to test and verify that it should be strings?  Feel free to create a pull request for this change.

**Comment by steven-t-h** [comment]
@MrRob I've verified this in 2022.2, 2023.1, and 2024.1. PR created.
