### ISSUE TITLE
Typo: `findMatrixSublistLineWIthValue`

### ISSUE THREAD

**Issue by krisre-sigmabold** [headintheclouddev/typings-suitescript-2.0#273]
https://github.com/headintheclouddev/typings-suitescript-2.0/blob/a5148c0618012f94d8b1e31db20ebc87330f8dcc/N/record.d.ts#L488

The "I" in "With" appears to be incorrectly capitalized...

**Comment by MrRob** [comment]
@krisre-sigmabold Thank you for pointing that out!  I will have this updated in the next release here.
