### ISSUE TITLE
Form method getTabs() should return string[]

### ISSUE THREAD

**Issue by sjbartley** [headintheclouddev/typings-suitescript-2.0#281]
Quick correction:
You have Form method getTabs() returning Tab[], but this should be string[] per https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4339699645.html.

interface Form extends BaseForm {
...
getTabs(): string[];
...
}

**Comment by MrRob** [comment]
@sjbartley Thank you for this!  I will include this in the next upcoming release.
