### ISSUE TITLE
Undocumented overloads

### ISSUE THREAD

**Issue by ahowley** [headintheclouddev/typings-suitescript-2.0#287]
I noticed some overloaded functions have multiple signatures documented (i.e. `Record.getValue(fieldId: string)` vs. `Record.getValue(options: { fieldId: string })`) while others that behave as expected with positional arguments are missing their overloaded signatures, only allowing a "proper" `options` object to be passed.

Is this something that warrants fixing/adding the overloaded signatures, removing the overloaded signatures for the few functions that do have them to remain consistent with the documentation, or is it fine as is? I would be happy to make inroads on this as I come across overloads that can be added.

Not needing a new object for every API call is less cumbersome to write, less verbose, and takes advantage of the benefits of strong typing. Theoretically it's (extremely marginally) more performant, while also providing the benefit of making it easier to port .js SuiteScripts to .ts SuiteScripts, and allowing several example snippets in the documentation to not cause signature type errors, which can be confusing to come across for those new to writing SuiteScript code (albeit that code is not always very reliable to begin with).

All that said, I certainly could understand arguments against it, so I figured I'd open the floor for discussion and see if there's any interest in these receiving a facelift. I'm still hoping to find time to [comb for more undocumented nulls](https://github.com/headintheclouddev/typings-suitescript-2.0/pull/282), so I could work on this in tandem.

**Comment by MrRob** [comment]
@ahowley I appreciate you raising the topic!  My opinion is that we should generally steer clear from undocumented overloads.  In theory they could stop working at any time.  The only ones I'm generally okay with are record.getValue and record.setValue.  I wouldn't really want to add any others into the mix here.

**Comment by ShawnTalbert** [comment]
I agree with @MrRob but go further and argue to not include _any_ of the undocumented overloads. I wish

I also agree with @ahowley in the NS API being cumbersome and verbose, but don't see how it loses any strong typing advantages. It's unfortunate that NS jumped on the bandwagon of 'all functions take an object! woo woo!'.  Not only is it more verbose, it gets in the way of leveraging some functional programming patterns.

p.s. @ahowley my biased recommendation to make NS code more pleasant is to use https://github.com/ExploreConsulting/netsuite-fasttrack-toolkit-ss2. Among other things, the NFT library provides a thin layer that makes working with NetSuite record data plain old TypeScript 101 objects and collections.

**Comment by ahowley** [comment]
I agree with @ShawnTalbert on principle about removing the undocumented overloads, but in practice I'm grateful they're in there haha. I don't think it's a huge deal either way, just noticed the discrepancy and wanted to offer in case it was needed!

And thank you for the recommendation, this looks _really_ nice 🚗💨 I've been pondering for a while what the generics headache would look like to allow for typed getValue() and setValue() (beyond just `FieldValue`, which is probably the most robust approach but requires you memorize JS type equivalents for NS field types), this seems like a nice option to help make that less painful (among other things)

**Comment by MrRob** [comment]
Hmm, what if as a compromise we just add clear comments in N/record to warn folks about the undocumented overloads?

**Comment by ahowley** [comment]
Do you mean updating the package to include them, but documenting that they're "unstable"? I could get behind this idea, but I also won't fight for it if people prefer it without them - I think both would be okay, they kind of reflect two different philosophies about how to wrestle with the state of SuiteScript (the possibility of undocumented things changing vs. the reality that they almost never seem to)

**Comment by MrRob** [comment]
@ahowley Yes, basically I don't want to add more undocumented overloads, but I don't want to remove the ones we do have, as I think a lot of people use them!
