### ISSUE TITLE
Uncomment HashAlg.SHA1 and HashAlg.MD5 from crypto.d.ts

### ISSUE THREAD

**Issue by rsbueno-felipe** [headintheclouddev/typings-suitescript-2.0#292]
Hi, 

First, congrats on this project, it helps a lot when dealing with NS types in typescript.

We have a valid use for SHA1 and MD5 encryption algorithms, and we would like to use them directly from crypto.d.ts. Currently we had to customize this file in order to use the enum values.

Could you please uncomment them from crypto.d.ts HashAlg enum? I know they are not recommended for encryption but in some cases we have to use them.

Thanks!

**Comment by MrRob** [comment]
@rsbueno-felipe I'm glad you've found this project helpful!

I know there is a "feature" for switching support for HMAC-SHA1 on and off in NetSuite, but is MD5 still supported at all?

Also, are you using these algorithms frequently, or is this more of a seldomly needed workaround?  If it's the latter, I'd recommend maybe just using @ts-ignore or "as any" to get around this.

I'm curious if any other contributors have thoughts on this?

**Comment by rsbueno-felipe** [comment]
Hi @MrRob , 

Yeah, we use both frequently. In both cases, we use it because we integrate with endpoints from external tax authorities that require this type of encryption.

SHA1 is used for XML electronic signature. MD5 is used to pass some encrypted parameters in the body of a request.

We can still use @ts-ignore as you suggest, but considering both algorithms are still supported by NS, I suggested we uncomment the values.

Thanks for the quick response!

**Comment by MrRob** [comment]
@rsbueno-felipe Okay, I will add them back in.  I'm still curious about MD5 though, as it no longer shows up in the documentation.  Does it "just work" anyway?  Or is there somewhere in NetSuite that you have to switch it on or off?

**Comment by ShawnTalbert** [comment]
My 2 cents here is to stick to reality - if SHA1 and MD5 are indeed still
working, I'd expect our types to reflect that. When/if it's ever removed,
then we'd remove it here.

This wouldn't be the first time this library is more correct than NS's
documentation. I feel that this lib has always followed the documentation
foremost, but also blending in some reality even (especially?) when reality
differs from the documentation.

**Comment by rsbueno-felipe** [comment]
Hi @ShawnTalbert @MrRob ,

I tested here, I'm getting a HASHING_ALGORITHM_IS_NO_LONGER_VALID for both MD5 and SHA1. 

We were able to use them in the past, but the currently workflow, although still implemented, is not being used. Apologies for that.

We can keep the library as it is. Thanks for your answers and sorry for the inconvenience.

**Comment by MrRob** [comment]
Lol okay, no worries, I'll comment them out again here then!  Thank you for verifying
