### ISSUE TITLE
SSS_INVALID_TYPE_ARG when calling certificateControl.findCertificates with options.subsidiary as string

### ISSUE THREAD

**Issue by rsbueno-felipe** [headintheclouddev/typings-suitescript-2.0#293]
When we call the method findCertificates in certificateControl.d.ts, passing options.subsidiary as string, according the FindCertificatesOptions interface, it leads to an error in NetSuite (SSS_INVALID_TYPE_ARG). I tested with something like "1234".

I suggest to change the subsidiary type to number in certificateControl.d.ts FindCertificatesOptions interface. This way we enforce the right type for this parameter.

Thanks!

**Comment by MrRob** [comment]
@rsbueno-felipe Definitely, I'll push out a fix for this in the next update :)
