### ISSUE TITLE
Making record id property nullable

### ISSUE THREAD

**Issue by sjbartley** [headintheclouddev/typings-suitescript-2.0#296]
I think N/record.d.ts should have ClientCurrentRecord (line 566) with:

`id: number | null;`

This property is usually null when isNew is true, but there are exceptions such as in the afterSubmit entrypoint (i.e. isNew may be true, but id is always non-null).

**Comment by sjbartley** [comment]
Sorry, it may be that this really needs to be combined with further interface changes indicating when it id is not null:

E.g.

```
interface afterSubmitContext {
    newRecord: N_record.Record & { id: number };
    oldRecord: N_record.Record;
    type: UserEventType;
    UserEventType: UserEventTypes;
}
 
```

**Comment by MrRob** [comment]
@sjbartley That sounds cool, can you do a pull request?

**Comment by sjbartley** [comment]
Will do.

Given this may impact people's code, I thought I'd see if there was a reason or opinion I needed to know about.

Thank you for your work on this repository.
