### ISSUE TITLE
Remove need for ///<ref> tag

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#3]
can we look at removing the need for this proprietary ///ref tag in order to use these typings?

**Comment by johnogle222** [comment]
It's my understanding that once #4 is resolved the ref tags will no longer be necessary. Am I missing something there?

**Comment by ShawnTalbert** [comment]
It is true that resolving #4 will hopefully resolve this, but this can be resolved independently as well. 

By way of example, I avoid using ///ref tags in my code via a hacky symlink to surface an N/ folder containing the NFT declarations virtually at the top level of the project. Then use only native `import` statements in TS files.

**Comment by johnogle222** [comment]
This is closed with #4
