### ISSUE TITLE
TS7043 error in workbook.d.ts

### ISSUE THREAD

**Issue by Extend-Apps** [headintheclouddev/typings-suitescript-2.0#304]
We use strict: true in our tsconfig and a recent change has caused issues.

export const DescendantOrSelfNodesSelector;

We should explicitly type this exported variable

**Comment by ShawnTalbert** [comment]
Probably a good idea to have strict enabled for this repo's tsconfig as a whole, to be safe?

**Comment by Extend-Apps** [comment]
I can update my PR to include that change as well?  Or separate PR?

**Comment by MrRob** [comment]
Let's do a separate one please
