### ISSUE TITLE
/N/types file ... UserEvent beforeLoadContext

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#32]
So,

In SS1.0, the beforeLoad passed in an nlobjRequest object, but in the SS2.0 ... it did not.

But, after further investigation ... it actually DOES exist.

So, in the beforeLoadContext interface, can you please add the following property?

request: N_http.ServerRequest

NOTE: yes, its http and NOT https.  Don't ask me why.

**Comment by johnogle222** [comment]
This is fixed in 2016.2.12
