### ISSUE TITLE
Types functions return "Object"

### ISSUE THREAD

**Issue by Uniphix** [headintheclouddev/typings-suitescript-2.0#34]
You have a lot of function fields that return Object, when it comes to typing cast such as something like this below:

`interface SearchLookupFieldsFunction {
    promise(options: SearchLookupFieldsOptions): Promise<Object>;
    (options: SearchLookupFieldsOptions): Object;
}`

should be

`interface SearchLookupFieldsFunction {
    promise(options: SearchLookupFieldsOptions): Promise<any>;
    (options: SearchLookupFieldsOptions): any;
}`

If I do something like this

`let fields = search.lookupFields(...);` 

I have to force cast it to be

`let fields: any = search.lookupFields(...);`

Ben

**Comment by johnogle222** [comment]
Thanks for your report! `Object` has been updated to `any` now in v2016.2.13
