### ISSUE TITLE
N/log issues

### ISSUE THREAD

**Issue by Uniphix** [headintheclouddev/typings-suitescript-2.0#35]
Accordingly to the NetSuite documentation:

log.debug, log.emergency, log.error, log.audit contains

"details" or the 2nd parameter should be "any" not "string"  Otherwise I'd have to force it to be JSON.stringify() which "the 2nd parameter already handles this accordingly to the docs.

Ben

**Comment by johnogle222** [comment]
Thanks for the report! Log details will now accept `any`. This will make my life a lot easier too haha
