### ISSUE TITLE
Refactor of record Type enum

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#38]
So, right now, you've duplicated the record Type enum in the Search definition file.

Instead, I suggest adding the following to the tope of the search.d.ts file
import {Type} from './record';

And, remove the duplicated Type enum

I found this issue when I attempted to use the 'context.newRecord.type' in a search.lookupFields function.  The 'Type' we not compatible, but we all know they should be.

**Comment by johnogle222** [comment]
The enums actually are slightly different. The first instance that comes to mind is TRANSACTION exists on search.Type but not record.Type.

In situations like this, thus far I've been casting the Type to a string:
`<string>N_search.Type.SALES_ORDER`
and forcing a cast like this makes sure you at least think about what you're sending from one to the other in case you're using incompatible types.

I'm open to suggestions on how to potentially detect incompatibilities. I'm just not sure if something like that is possible here.

**Comment by darrenhillconsulting** [comment]
Not sure if its possible, but what a 'base' enum for records, and have each module 'extend' it?

**Comment by ShawnTalbert** [comment]
I haven't tried with TS 2.2 but it wasn't possible to extend enums in
earlier versions..

**Comment by jcormont** [comment]
Why not convert this to an interface like

```typescript
interface SearchType exends RecordType {
  TRANSACTION: "transaction" // or just : string
  // ...
}
declare var Type: SearchType;
```

That would have the exact same effect as an enum (and is more accurate since this is actually an object internally).

**Comment by ShawnTalbert** [comment]
I'd be loathe to write such a complex type signature for such a simple concept. If you can enhance your type definition such that the function remains a simple `function f( theenum: <sometype>)` I'd be all in.

**Comment by jcormont** [comment]
You mean like this...? 😄 

![image](https://cloud.githubusercontent.com/assets/1476188/24493690/5634c6d0-1562-11e7-8ca8-9932da048ec0.png)

![image](https://cloud.githubusercontent.com/assets/1476188/24493740/7cc9162a-1562-11e7-9d0e-c354cdbc1740.png)

**Comment by johnogle222** [comment]
Wouldn't that reject custom record types though, which would be required here?

**Comment by darrenhillconsulting** [comment]
Just to clean the 'Issues' up a little, this really isn't an issue.
