### ISSUE TITLE
Missing functions in ui/serverWidget

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#5]
Specifically the Sublist interface ...

I added the following function ...

getField(options: GetFieldOptions): Field;  (I added it at line 330 ... in the Sublist interface)

This appears to be undocumented by Netsuite (weird), but its there (and crucial) if you want to hide sublist fields in a beforeload.

**Comment by darrenhillconsulting** [comment]
Update:  if should ready

getField(options: IDOptions): Field;

**Comment by johnogle222** [comment]
Hi Darren,

Would you be able to submit a pull request for this one? It sounds like you've already got the changes written :)

Thanks,
John

**Comment by darrenhillconsulting** [comment]
No problem,  Done.

**Comment by johnogle222** [comment]
Fixed in #6
