### ISSUE TITLE
N/xml ImportNode definition incorrect

### ISSUE THREAD

**Issue by t3hchipmunk** [headintheclouddev/typings-suitescript-2.0#51]
The importNode definition is defined as [importNodes.](https://github.com/headintheclouddev/typings-suitescript-2.0/blob/master/N/xml.d.ts#L149) It should be importNode per [NetSuite](https://netsuite.custhelp.com/app/answers/detail/a_id/43903).

**Comment by johnogle222** [comment]
Thanks for the report! This is fixed now in 2017.1.24.
