### ISSUE TITLE
N/runtime:isFeatureInEffect

### ISSUE THREAD

**Issue by jerry-atom** [headintheclouddev/typings-suitescript-2.0#52]
Hi.
According to documenation of SuiteScript 2.0 N/runtime:isFeatureInEffect function does not accept an object with property "name". It requires a property "feature" like this:
```typescript
interface FeatureOptions {
    /** The internal ID of the feature to check. */
    feature: string;
}
```
Anyway, Thank You for this package, it is a Great Job.

**Comment by johnogle222** [comment]
Thanks for the report, Jerry!

This should be fixed now in v2017.2.5.
