### ISSUE TITLE
Compiled 'Export' Object Not Available in Public Modules?

### ISSUE THREAD

**Issue by JonnyBoy333** [headintheclouddev/typings-suitescript-2.0#54]
I just tried making a public module using typescript and while it works correctly in the account I created it in, if I put it in a bundle and install it in another account, it no longer works. Instead, I get an error stating that the exported function is not available.

So I know that typescript makes an assumption that an 'export' object is always available in CommonJS. This is why you see `Object.defineProperty(exports, "__esModule", { value: true });` at the top of each compiled script and then `exports.test = test` at the bottom instead of `return { test: test }`. I have a feeling that the exports object is not available for some reason in a public module coming from a bundle.

I tested this by switching between `exports.test = test` and `return { test: test }` in the second account and the second way works correctly, the first does not.

Anyone know of a way to solve this? Or have typescript not rely on the 'exports' object when compiling?

Here is my sample module code if you want to test.
Typescript:
```
/**
 * @NApiVersion 2.x
 * @NModuleScope public
 * author: me
 * Date: 2/8/17
 * Version: 1.0
 */

import * as log from 'N/log';

export function test() {
    log.debug('Starting Up', '<--------------');
}
```

Compiled:
```
/**
 * @NApiVersion 2.x
 * @NModuleScope public
 * author: me
 * Date: 2/8/17
 * Version: 1.0
 */
define(["require", "exports", "N/log"], function (require, exports, log) {
    Object.defineProperty(exports, "__esModule", { value: true });
    function test() {
        log.debug('Starting Up', '<--------------');
    }
    exports.test = test;
    //return { test: test } <----- This will work if uncommented
});
```

**Comment by johnogle222** [comment]
I don't have the prettiest solution, but basically I run my compilation through a custom gulp plugin after tsc has done its thing:

```
var through = require('through2');
var gutil = require('gulp-util');
var PluginError = gutil.PluginError;
var os = require('os');

var PLUGIN_NAME = 'gulp-amd-to-netsuite';
var defineLineRegex = /^define\(\["require", "exports",? ?(.*)\], function \(require, exports,? ?(.*)\) \{$/
var lastLineRegex = /^\}\);$/

// plugin level function (dealing with files)
function gulpCompile() {
  var s = through.obj(function(file, enc, cb) {
    if (file.isStream()) {
      this.emit('error', new PluginError(PLUGIN_NAME, 'Streams are not supported!'));
      return cb();
    }

    if (file.isBuffer()) {
      var lines = file.contents.toString().split('\n');
      var outLines = [];
      for (var i=0; i<lines.length; i++) {
        var line = lines[i];
        var matches = line.match(defineLineRegex)
        if (matches && matches.length > 1) {
          line = "define(["+matches[1]+"], function ("+matches[2]+") {";
          outLines.push(line);
          outLines.push("    var exports = {};");
        } else if (line.match(lastLineRegex) && i >= lines.length-2) {
          outLines.push("    return exports;");
          outLines.push(line);
        } else {
          outLines.push(line);
        }
      }
      file.contents = new Buffer(outLines.join('\n'));
      s.push(file);
      cb();
    }
  });

  // returning the file stream
  return s;
};

// exporting the plugin main function
module.exports = gulpCompile;
```

This takes out the `require` and `exports` imports that are emitted from tsc and defines a local exports object which then gets explicitly returned.

Is this a possibility for you?

**Comment by JonnyBoy333** [comment]
@johnogle222 Sorry for not responding earlier. Gulp is an option but I try not to add overhead when I can help it, I've also got a few people on my team that I'd have to get to adopt the solution as well.

I found a better way to do this is to redefine the export object itself to the items you are exporting. Typescript seems to correctly compile this into what you would expect the commonJS to look like. A more detailed explanation as to why this works is here: https://stackoverflow.com/questions/47297768/typescript-compilation-of-requirejs-module-generates-line-object-defineproperty.

Example typescript file:
```
/**
 * @NApiVersion 2.x
 * @NModuleScope public
 * author: me
 * Date: 2/8/17
 * Version: 1.0
 */

import * as log from 'N/log';

function afterRecordSubmit() {
    log.debug('Starting Up', '<--------------');
}

export = { afterRecordSubmit }
```

Compiles to:
```
/**
 * @NApiVersion 2.x
 * @NModuleScope public
 * author: me
 * Date: 2/8/17
 * Version: 1.0
 */
define(["require", "exports", "N/log"], function (require, exports, log) {
    function afterRecordSubmit() {
        log.debug('Starting Up', '<--------------');
    }
    return { afterRecordSubmit: afterRecordSubmit };
});
```

Now you do still see the 'require' and 'exports' modules getting passed in but they are not getting used for anything and therefore have no effect. This way public modules work great. I don't think NetSuite explicitly supports using the exports object with SuiteScript so I honestly think that this should be the recommended solution documented in the readme...

**Comment by johnogle222** [comment]
Huh, that's awesome @JonnyBoy333. Thanks for sharing!
