### ISSUE TITLE
record.create is not recognized as function

### ISSUE THREAD

**Issue by zsf3** [headintheclouddev/typings-suitescript-2.0#55]
I am using VSCode 1.18 and Typescript 2.4.2 and getting following error on `record.create` function and `record.Type` enumeration. These are standard members and properties of `record` object as documented by NetSuite in their help.

What can I do to fix this issue in Typescript?

![image](https://user-images.githubusercontent.com/12393295/32877345-f0440a04-cac2-11e7-9ca8-e4e52096ab6d.png)

**Comment by johnogle222** [comment]
Hmm is it possible that you imported as `record` but then redefined record somewhere else? In VSCode for me if I try to call the function `record.foo` I get the error message:

`[ts] Property 'foo' does not exist on type 'typeof "/Users/johnogle/src/g5-suitescripts/node_modules/@hitc/netsuite-types/N/record"'.`

The type `Record` is what's returned when you create or load a record using the module.

**Comment by zsf3** [comment]
No, I don't think so. I am still getting same error. 

When I dug deeper into the `record.d.ts` file inside the module, I found out that `Record` class does not have any member with name `create`, instead `create` is a function which is exported separately like this: `export var copy: RecordCopyFunction;`

Here is my complete code sample with imports:

```javascript
    import {EntryPoints} from 'N/types'
    import {Record} from 'N/record'

    define(['N/record', 'N/log'], function(record: Record, log) {

        function afterSubmit(context: EntryPoints.UserEvent.afterSubmitContext) {
            if (context.type !== context.UserEventType.CREATE)
                return;
            var customerRecord = context.newRecord;
            if (customerRecord.getValue('salesrep')) {
                var call = record.create({
                    type: record.Type.PHONE_CALL,
                    isDynamic: true
                });
                call.setValue('title', 'Make follow-up call to new customer');
                call.setValue('assigned', customerRecord.getValue('salesrep'));
                call.setValue('phone', customerRecord.getValue('phone'));
                try {
                    var callId = call.save();
                    log.debug('Call record created successfully', 'Id: ' + callId);
                } catch (e) {
                    log.error(e.name);
                }
            }
        }

        return {
            afterSubmit: afterSubmit
        };
        
    });

**Comment by johnogle222** [comment]
Ahh I see now. You'll want to make tweaks to your structure like this:
```typescript
import {EntryPoints} from 'N/types'
import * as record from 'N/record'
import * as log from 'N/log'

export function afterSubmit(context: EntryPoints.UserEvent.afterSubmitContext) {
  if (context.type !== context.UserEventType.CREATE)
    return;
  var customerRecord = context.newRecord;
  if (customerRecord.getValue('salesrep')) {
    var call = record.create({
      type: record.Type.PHONE_CALL,
      isDynamic: true
    });
    call.setValue('title', 'Make follow-up call to new customer');
    call.setValue('assigned', customerRecord.getValue('salesrep'));
    call.setValue('phone', customerRecord.getValue('phone'));
    try {
      var callId = call.save();
      log.debug('Call record created successfully', 'Id: ' + callId);
    } catch (e) {
      log.error(e.name);
    }
  }
}
```

A few issues with what you had:
1. import + define is redundant
2. You were importing the loaded Record type from the module instead of the module itself
3. I added an import for log at the top as well

Does that make sense?

**Comment by zsf3** [comment]
NetSuite requires a module which is created via `define`  in the user event. How will your code accomplish that?

**Comment by cancerberoSgx** [comment]
@zsf3 define() is created by the typescript compiler - for that you must configure "module": "amd" in your tsconfig.json as documented in the readme. In summary import and export are translated to defined() in the compiled js (that you need to upload to ns)

**Comment by johnogle222** [comment]
@zsf3 Also see the following for reference in case you're new to TypeScript: https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html
