### ISSUE TITLE
type definition of columns (on Search interface)

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#68]
I've struggled with this one a bit.  The property definition for columns on the Search object is 
`columns: (Column[] | string[]);`

The problem I have is when I try to
`searchObj.columns.push(search.createColumn({name: 'tranid'}));`

I then get an error 
> Error:(120, 5) TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((...items: string[]) => number) | ((...items: Column[]) => number)' has no compatible call signatures.

I typically just modify the search.d.ts file and change the definition to
`columns: Column[];`

I've tried everything from casting to Column, to playing around with the definition (To be honest, I'm not really sure with the parentheses do in the type definition?)

**Comment by johnogle222** [comment]
I believe I have this issue fixed in the (soon to be released) v2017.2.24. Let me know if that works for you!

**Comment by darrenhillconsulting** [comment]
Nice work @johnogle222 .  Fixed!
