### ISSUE TITLE
npm out of sync?

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#70]
Something odd just happened.

So, I installed the typings via npm (npm install --save-dev @hitc/netsuite-types), as I always do.  Cool.
It says I've got version 2017.2.25.  Great.

I start get TypeScript errors with my BundleInstall script, saying that there is no such member onAfterInstallParms.  I take a peek at the types.d.ts (locally) and suer enough it should be onAfterInstallContext (Which is odd, because I contributed that interface).

So, just to see when/who made that change, I came here and had a look at types.d.ts ... last editor was me.  And its onAfterInstallParms.  What's also odd is the package.json here say 2017.2.24

I won't claim to be an expert here, where is 2017.2.25?

**Comment by cancerberoSgx** [comment]
are you sure your changes were pushed / published to npm.org ? i would try the following just in case:  
```
rm -rf node_modules package-lock.json
npm install --save-dev https://github.com/headintheclouddev/typings-suitescript-2.0
```

**Comment by darrenhillconsulting** [comment]
I don't manage the publishing to npm.  @johnogle222 ?

**Comment by johnogle222** [comment]
Hey Darren. Sorry about the name change. I didn't realize people were importing that directly and I wanted to rename it to be more consistent with the other interfaces in that file. Maybe it would make sense to add some aliases of the old names such that your code base(s) aren't throwing errors?

I'm pretty sure 2017.2.25 was published to npm. Regardless of that though is everything working as expected now with 2017.2.26?

**Comment by darrenhillconsulting** [comment]
Everything looks good, thanks John.
