### ISSUE TITLE
Using SS1.0 types

### ISSUE THREAD

**Issue by darrenhillconsulting** [headintheclouddev/typings-suitescript-2.0#75]
Ok, this really isn't an issue and more of a question.  I noticed there type definitions available in here, how to I import them or take advantage of them?

**Comment by johnogle222** [comment]
You need to add something like this at the top of your SSV1 files (at least in WebStorm):
```/// <reference path="../../node_modules/@hitc/netsuite-types/SuiteScriptV1.d.ts" />```
