### ISSUE TITLE
using third party node modules

### ISSUE THREAD

**Issue by cancerberoSgx** [headintheclouddev/typings-suitescript-2.0#76]
More than an issue this is a question, I think is important. 

Did you figure out a way of handle third party libraries. Just to put an example, imagine I want to use https://github.com/typestack/class-validator so if I do :

```sh
npm install class-validator --save
```

and then in some of my .ts files I import the library: 

```js
import {validate} from "class-validator";
```

It should work. Nevertheless, I get the following error when creating the script in ns : "Fail to evaluate script: {"type":"error.SuiteScriptModuleLoaderError","name":"MODULE_DOES_NOT_EXIST","message":"Module does not exist: /class-validator.js","stack":[]}"

Would be ideal if tsc or some plugin create this file automatically (with amd syntax) . I'm not sure if this is an issue of this library (probably  not) and probably I could solve this with special typescript configuration or perhaps using some typescript plugin, but I'm not ts expert. 

I would very like to know if you have some workaround for this or how / if you are handling this. If not, I would investigate this further since IMO is important and ideal to make this work, but first wanted to ask you. 

Thanks, any tip or idea is most welcome.

**Comment by johnogle222** [comment]
Yeah this library only provides type data for the NetSuite API.

If you want to import external libraries into your NetSuite code you have a few options available to you.

1. Add the library to the File Cabinet directly and import from there. If the library already is AMD-compatible then it should work relatively well without too many issues. If it isn't then you can shim it in - look up the require.config options in the NetSuite help and add a @NSAMDConfig tag to your header JSDoc comment.

2. Compile the library into your file using something Webpack and let it sort out the internal requirements. This gets pretty complicated but can make a lot of sense if you're working with tons of imports. As NetSuite hasn't yet moved module loading to HTTP 2.0 it can start to very noticeably degrade page load performance when you have more than say 10-15 imports on the client side.

3. Don't use external libraries. Sometimes this is the simplest and best option.

**Comment by dglenn4402** [comment]
> Thanks John for the fast reply. Glad you had this problem too. I think this is kind of important - having this kind of automated will bring netsuite more close to the npm world I think which will boost suitescript development a lot.
> 
> I will try to research this with more time and perhaps contributing a little paragraph in the readme about this and best practices or a wiki or a small project example.
> 
> I wonder why typescript won't compile something in node_modules even if I require it relatively , i.e
> 
> ```js
> import {validate} from "./node_modules/class-validator/index"
> ```
> 
> For some reason is treating modules in node_modules in a special way - I think it should compile those just like my other files, will research on this direction although I'm probably wrong since I'm not ts expert.
> 
> Thanks again

Did you ever have any luck with this? I would like to compile my 3rd party node modules as you described above, but have yet to find a workable solution.

Thanks!

**Comment by michoelchaikin** [comment]
I've played around this before and have a sample webpack config here:

https://github.com/michoelchaikin/netsuite-webpack

Whilst I personally haven't used this in a production project, I have heard
from someone who did successfully.
