### ISSUE TITLE
Record.id should be a number?

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#8]
The `id` property of the Record type is documented as a number in NS [docs](https://system.sandbox.netsuite.com/app/help/helpcenter.nl?fid=section_4296706656.html) , but it is of type **string** in `record.d.ts`.

**Comment by ShawnTalbert** [comment]
I submitted a PR that includes this small change.

**Comment by johnogle222** [comment]
Merged in #9
