### ISSUE TITLE
Types for SuiteGL?

### ISSUE THREAD

**Issue by ShawnTalbert** [headintheclouddev/typings-suitescript-2.0#90]
Looks like SuiteGL is still locked in SS1.0 mode, but I can't find any type declarations for it.

Do we have type definitions for SuiteGL's `customizeGlImpact()`,  and if not, should we create some?

**Comment by MrRob** [comment]
Hey Shawn,

I just pushed up a new version for 2018.2, and I threw in the type
definition file I have for SuiteGL into the base directory there.  There
may be a cleaner way to do this, but that hopefully that works for now!

Thanks

Robbie

*Robin Mitchell*
President
503-957-8114 *US Mobile*
07376 230976 *UK Mobile*
robin.mitchell@headintheclouddev.com

Head in the Cloud Development
http://www.headintheclouddev.com
Check my calendar availability
<http://www.google.com/calendar/embed?src=robin.mitchell%40ndos.co>

**Comment by ShawnTalbert** [comment]
Hah, ironic that I just created a similar file... though I think mine may be a bit more complete. We should also add mention of it in the README so people know it exists?

If you like, I can update your file with any extra stuff from mine, and add a blurb to the readme?

**Comment by darrenhillconsulting** [comment]
So, I see SuiteGL.d.ts, how do I use it?  

import {CustomLine} from './node_modules/@hitc/netsuite-types/SuiteGL'?

**Comment by MrRob** [comment]
I just use it by including a <reference> tag to it.  See the attached screenshot of a simple test file I set up, just in the main ssv1 folder of the project.
<img width="1414" alt="screen shot 2018-09-10 at 13 38 08" src="https://user-images.githubusercontent.com/448678/45298009-12cec100-b4ff-11e8-85a0-ba0943f8700d.png">

**Comment by darrenhillconsulting** [comment]
Of course!  Thanks Robin!


*Darren Hill*
*Owner*
*Darren Hill Consulting Inc.*
16 Faludon Dr
Georgetown, ON  L7G1H7
Office: 416.856.6220
www.darrenhillconsulting.ca

**Comment by ShawnTalbert** [comment]
FYI, I think for SS1-like code you can also just add the .d.ts fle to your `tsconfig.json` and it will be included?
We try to avoid any 'custom' tags in our code like `//reference...`

**Comment by MrRob** [comment]
@ShawnTalbert That sounds interesting - but how exactly would you add it?  I'm not very familiar with the tsconfig.json setup.  Thanks!

**Comment by ShawnTalbert** [comment]
> @ShawnTalbert That sounds interesting - but how exactly would you add it? I'm not very familiar with the tsconfig.json setup. Thanks!

you can add it to the `files` property of tsconfig.json. like:
```
... other stuff
"files" : [
"path/to/.d.ts/file",
"mysource.ts"
],
... other stuff

**Comment by MrRob** [comment]
@ShawnTalbert I see!  That makes sense, but I tried it, and for some reason it isn't working - WebStorm is saying nlapiLogExecution is undefined now.  Have you gotten that to work yourself there?

**Comment by ShawnTalbert** [comment]
@MrRob try also including your main SS1 declarations `.d.ts` file in the `files` list.
