### ISSUE TITLE
missing property "type" in SearchLoadOptions

### ISSUE THREAD

**Issue by jerry-atom** [headintheclouddev/typings-suitescript-2.0#93]
Hi.

There is missing an optional string property "type" in SearchLoadOptions interface.

SuiteScript documentation says:

> Property SearchLoadOptions.type is required if the saved search to load uses a standalone search type, optional otherwise.
> The search type of the saved search to load. Use a value from the search.Type enum for this parameter.
> 
> This parameter is required if the saved search to load uses a standalone search type. A standalone search type is a search type that does not have a corresponding record type. Typically, the search type of the saved search can be determined automatically based on the corresponding record type. In this case, this parameter is not required. For standalone search types, you must specify the search type explicitly using this parameter.
> 
> The following is a list of standalone search types:
> - DeletedRecord
> - EndToEndTime
> - ExpenseAmortPlanAndSchedule
> - RevRecPlanAndSchedule
> - GlLinesAuditLog
> - Crosschargeable
> - FinRptAggregateFR
> - BillingAccountBillCycle
> - BillingAccountBillRequest
> - BinItemBalance
> - PaymentEvent
> - Permission
> - GatewayNotification
> - TimeApproval
> - RecentRecord
> - Role
> - SavedSearch
> - ShoppingCart
> - SubscriptionRenewalHistory
> - SuiteScriptDetail
> - SupplyChainSnapshotDetails
> - SystemNote
> - TaxDetail
> - TimesheetApproval
> - Uber
> - ResAllocationTimeOffConflict
> - ComSearchOneWaySyn
> - ComSearchGroupSyn
> - Installment
> - InventoryBalance
> - InventoryNumberBin
> - InventoryNumberItem
> - InventoryStatusLocation
> - InvtNumberItemBalance
> - ItemBinNumber

**Comment by MrRob** [comment]
Awesome, I added that in, thank you Jaroslav!

*Robin Mitchell*
President
503-957-8114 *US Mobile*
07376 230976 *UK Mobile*
robin.mitchell@headintheclouddev.com

Head in the Cloud Development
http://www.headintheclouddev.com
Check my calendar availability
<http://www.google.com/calendar/embed?src=robin.mitchell%40ndos.co>
